# Variaveis
@baseUrl = http://localhost:3333


# Health Check
GET {{baseUrl}}/health

###

# Trazer Rooms
GET {{baseUrl}}/rooms

###

# Criar nova sala
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
    "name": "Sala de Teste",
    "description": "Esta é uma sala de teste para verificar a criação de salas."
}
